version: '2.10.2'
services:

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./server/pkg/uploads/:/usr/src/app/pkg/uploads/
    depends_on:
      - mongo

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4000:80
    restart: on-failure
    depends_on:
      - server

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
